# Generated by Django 5.0 on 2024-10-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
